version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
            - run: npm run lint
            - run: npm test
            - run: npx commitlint --from HEAD~1 --to HEAD --verbose
workflows:
    build:
      jobs:
        - build